export const PREDEFINED_OPTIONS = {
  virtualMachine: {
    providers: [
      "VMware Workstation",
      "VMware vSphere",
      "VirtualBox",
      "Hyper-V",
      "Parallels Desktop",
      "QEMU/KVM",
      "Proxmox VE",
      "Citrix XenServer",
      "Oracle VM",
      "Red Hat Virtualization",
    ],
    operatingSystems: [
      "Ubuntu 22.04 LTS",
      "Ubuntu 20.04 LTS",
      "Ubuntu 24.04 LTS",
      "CentOS 7",
      "CentOS 8",
      "RHEL 8",
      "RHEL 9",
      "Debian 11",
      "Debian 12",
      "Windows 10",
      "Windows 11",
      "Windows Server 2019",
      "Windows Server 2022",
      "macOS Monterey",
      "macOS Ventura",
      "macOS Sonoma",
      "Fedora 38",
      "Fedora 39",
      "openSUSE Leap",
      "Arch Linux",
      "Alpine Linux",
      "FreeBSD 13",
      "OpenBSD 7",
    ],
    hardwareConfigs: [
      "1 CPU, 1GB RAM",
      "1 CPU, 2GB RAM",
      "2 CPU, 2GB RAM",
      "2 CPU, 4GB RAM",
      "4 CPU, 4GB RAM",
      "4 CPU, 8GB RAM",
      "6 CPU, 8GB RAM",
      "8 CPU, 16GB RAM",
      "12 CPU, 24GB RAM",
      "16 CPU, 32GB RAM",
      "Custom Configuration",
    ],
    networkAdapters: [
      "NAT",
      "Bridged",
      "Host-only",
      "Internal Network",
      "NAT Network",
      "Generic Driver",
      "Cloud Network",
    ],
    storageSizes: [
      "10GB",
      "20GB",
      "40GB",
      "50GB",
      "80GB",
      "100GB",
      "120GB",
      "250GB",
      "500GB",
      "1TB",
      "2TB",
      "Custom Size",
    ],
  },
  physicalDevice: {
    manufacturers: [
      "Apple",
      "Dell",
      "HP",
      "Lenovo",
      "ASUS",
      "Acer",
      "MSI",
      "Samsung",
      "Microsoft",
      "Razer",
      "Alienware",
      "System76",
      "Framework",
      "ThinkPad",
      "MacBook",
      "Surface",
      "Custom Build",
    ],
    deviceTypes: [
      "Laptop",
      "Desktop",
      "Workstation",
      "Server",
      "Mini PC",
      "All-in-One",
      "Tablet",
      "Single Board Computer",
      "Network Attached Storage",
      "Router",
      "Switch",
      "Other",
    ],
    operatingSystems: [
      "macOS Monterey",
      "macOS Ventura",
      "macOS Sonoma",
      "Windows 10",
      "Windows 11",
      "Ubuntu 22.04 LTS",
      "Ubuntu 20.04 LTS",
      "Ubuntu 24.04 LTS",
      "Debian 11",
      "Debian 12",
      "CentOS 7",
      "CentOS 8",
      "RHEL 8",
      "RHEL 9",
      "Fedora 38",
      "Fedora 39",
      "Arch Linux",
      "openSUSE",
      "FreeBSD",
      "Chrome OS",
      "Android",
      "iOS",
      "iPadOS",
    ],
    hardwareConfigs: [
      "Intel i3, 8GB RAM, 256GB SSD",
      "Intel i5, 8GB RAM, 256GB SSD",
      "Intel i5, 16GB RAM, 512GB SSD",
      "Intel i7, 16GB RAM, 512GB SSD",
      "Intel i7, 32GB RAM, 1TB SSD",
      "Intel i9, 32GB RAM, 1TB SSD",
      "AMD Ryzen 5, 16GB RAM, 512GB SSD",
      "AMD Ryzen 7, 32GB RAM, 1TB SSD",
      "AMD Ryzen 9, 64GB RAM, 2TB SSD",
      "Apple M1, 8GB RAM, 256GB SSD",
      "Apple M1, 16GB RAM, 512GB SSD",
      "Apple M1 Pro, 16GB RAM, 512GB SSD",
      "Apple M1 Max, 32GB RAM, 1TB SSD",
      "Apple M2, 8GB RAM, 256GB SSD",
      "Apple M2, 16GB RAM, 512GB SSD",
      "Apple M2 Pro, 16GB RAM, 512GB SSD",
      "Apple M2 Max, 32GB RAM, 1TB SSD",
      "Apple M3, 8GB RAM, 256GB SSD",
      "Apple M3 Pro, 18GB RAM, 512GB SSD",
      "Apple M3 Max, 36GB RAM, 1TB SSD",
      "Custom Configuration",
    ],
    networkAdapters: [
      "Wi-Fi 6E (802.11ax)",
      "Wi-Fi 6 (802.11ax)",
      "Wi-Fi 5 (802.11ac)",
      "Gigabit Ethernet",
      "10 Gigabit Ethernet",
      "Bluetooth 5.3",
      "Bluetooth 5.2",
      "Bluetooth 5.1",
      "Bluetooth 5.0",
      "Thunderbolt 4",
      "Thunderbolt 3",
      "USB-C",
      "Multiple Adapters",
    ],
    storageSizes: [
      "128GB SSD",
      "256GB SSD",
      "512GB SSD",
      "1TB SSD",
      "2TB SSD",
      "4TB SSD",
      "500GB HDD",
      "1TB HDD",
      "2TB HDD",
      "4TB HDD",
      "8TB HDD",
      "Multiple Drives",
      "Custom Storage",
    ],
  },
}

// Backend API Configuration
export const API_CONFIG = {
  // Update this URL to match your backend endpoint
  BASE_URL: "http://localhost:3001",
  ENDPOINTS: {
    VM_STATUS: "/vms", // Detailed VM status information
    HEALTH_CHECK: "/vms/health", // Basic VM health/list information
  },
  // Request timeout in milliseconds
  TIMEOUT: 10000,
  // Refresh interval for live data in milliseconds
  REFRESH_INTERVAL: 5000,
}
